---
title: "CSAS 2026 Intro to R Notes"
author: "Tyler Adams"
date: "`r Sys.Date()`"
format:
  html:
    toc: true
    toc-depth: 2
    embed-resources: true
    code-fold: true
    theme: cosmo
editor: 
  markdown: 
    wrap: 72
---

Copy and paste code into the console, or click the 
run button located in the corner of your code block 
if you have the notes loaded in your IDE.

## R Syntax Example Code
```{r}

print("Hello world")

```

```{r}

x <- 2
y = 3

```

```{r}

# Addition
print(2 + 2)

# Subtraction
print(4 - 2)

# Multiplication (variables can be used too)
print(y * x)

# Division
print(x / 3)

# Exponentiation
print(x^2)
# or
print(x**2)

```

## Data Structure Example Code

```{r}

fav_color <- "black"

print(fav_color)

```

```{r}

x <- TRUE

print(x)


# Used for conditionals

if (x) {
  print("Yes")
}

```

```{r}

x <- 3.4
y <- 4
z <- 4L

print(class(x))
print(class(y))
print(class(z))

x <- as.integer(x)

print(class(x))
print(x)

```

## R Packages

```{r}

#install.packages("tidyverse")
library(tidyverse)

```

## Local Data Example Code

```{r}

# Creates the numerical data in the table
tab <- as.table(rbind(c(762, 327, 468, 593), c(484, 239, 477, 5930)))

# Labels the rows then the columns 
dimnames(tab) <- list(c("Honors", "Not Honors"), Grade = c("9th", "10th", "11th", "12th"))

```


## Manipulating Local Data

```{r}

# Only displays the first 2 columns
tab2 <- tab[, 1:2]
tab2

# Only displays the first row
tab3 <- tab[1,]
tab3

# Creates a new column avenging the grades by row
tab4 <- cbind(tab, Average = rowMeans(tab))
tab4

```

